name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build AMD64
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build_args: GOOS=linux GOARCH=amd64 ARCH=amd64
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-amd64
          no-cache: true

      - name: Build ARM64
        id: docker_build_arm
        uses: docker/build-push-action@v2
        with:
          build_args: GOOS=linux GOARCH=arm GOARM=5 ARCH=arm64
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-arm64
          no-cache: true

      - name: Create new manifest
        run: docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-amd64 ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest-arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}